import Head from 'next/head'
import Image from 'next/image'
import {setPageHeading} from "../Helper/Helper"
// @ts-ignore
import profile from "../public/profile/profile4.png"


export default function Home({setHeading, setCurrentPage}) {


  setPageHeading(setCurrentPage, setHeading, "");


  return (
    
    <>
      <Head>
        <title>My Portfolio</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>




      <main className='h-screen lg:h-full flex flex-col justify-center items-center '>


        <div className='flex flex-col justify-center space-y-5 h-screen lg:h-full lg:max-w-[65%]'>

          <h1 className='text-4xl font-bold mb-8 text-center'>I AM ANDILE</h1>

          <Image src={profile} objectFit='contain' />

          <p className=' font-light dark:font-thin tracking-widest '>My full name is Andile Nicolas Sithole, and i am currently a Computer Science and Informatics final year student @University of Johannesburge (2022).</p>

          <i className=' '>I am all about <b>reaching new heights.</b></i>

          <div className=' flex justify-around '>
            <button className='border border-gray-500 dark:bg-gray-900 bg-gray-300 py-1 w-28 hover:scale-105 hover:outline-1 hover:outline hover:outline-slate-400 shadow-sm shadow-slate-500 ease-out duration-500 cursor-pointer '>CV</button>
            <button className='border border-gray-500 dark:bg-gray-900 bg-gray-300 py-1 w-28 hover:scale-105 hover:outline-1 hover:outline hover:outline-slate-400 shadow-sm shadow-slate-500 ease-out duration-500 cursor-pointer '>Contact Me</button>
          </div>

        </div>
        
      
      </main>


    </>
  )
}
