import Head from 'next/head';
import Image from 'next/image';
import React, {useState} from 'react'
import { setPageHeading } from '../Helper/Helper';

// @ts-ignore
import profile from "../public/profile/profile3.png";

const Skills = ({setCurrentPage, setHeading}) => {


  const [next, setNext] = useState(false);

  setPageHeading(setCurrentPage, setHeading, "Skills");

    return (


        
      <>
      <Head>
        <title>My Skillz</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>


      {/* h-screen lg:h-full */}


      <div className='h-screen lg:h-full'>


        <p className=' text-center lg:text-left mb-5 text-sm'>Most Confident In</p>

        


      <div className='h-screen lg:h-full relative'>

      
        
        {/* h-screen lg:h-full */}
        <div className="bg-red-700 min-h-[50%] w-[91%] md:w-[96%] lg:w-[97%]  absolute top-6">
          
        </div>

        {/* h-screen lg:h-full */}
        <div className="bg-green-700 min-h-[50%]  w-[91%] md:w-[96%] lg:w-[97%]  absolute left-3 top-3">
          
        </div>

        {/* h-screen lg:h-full */}
        <div className="bg-gray-700 min-h-[50%]  w-[91%] md:w-[96%] lg:w-[97%] absolute left-6 ">



          <div className='mx-2 lg:mx-10'>

            <h1 className='mt-5 mb-1 lg:mb-5 text-2xl '>Technical Skills</h1>

            
            <div className='flex flex-col lg:flex-row lg:justify-between justify-center'>

            <h1 className={ (next==false?"":"invisible") + " lg:visible font-bold text-center"}>Frontend</h1>
            <h1 className={(next==false?"invisible ":""  ) + "font-bold lg:visible text-center"}>Backend</h1>

            </div>


            <h1 className={ ("")+ " text-2xl mt-10  mb-1 lg:mb-5 invisible lg:visible"}>Soft Skills</h1>


            <button onClick={()=> setNext(!next)} className=' lg:invisible absolute bottom-0 right-0 m-2'>{"->"}</button>

          </div>

          

        </div>

      </div>
      </div>

      
      


    </>
    )
}

export default Skills
